version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: root_cause_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
