'use client'

import { Shield } from 'lucide-react'

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#09090b] text-white px-6 py-20">
      <div className="max-w-3xl mx-auto">
        <a href="/" className="inline-flex items-center gap-2 text-zinc-400 hover:text-white transition-colors mb-10 text-sm">
          ← Back to home
        </a>

        <div className="flex items-center gap-3 mb-8">
          <Shield className="w-6 h-6 text-indigo-500" />
          <h1 className="text-3xl font-bold">Terms of Service</h1>
        </div>

        <p className="text-sm text-zinc-500 mb-8">Last updated: May 30, 2026</p>

        <div className="space-y-8 text-sm text-zinc-300 leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Sentinel-SRE (&quot;the Service&quot;), you agree to be bound by these
              Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
            <p>
              Sentinel-SRE is an open-source, AI-powered root cause analysis platform that:
            </p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Ingests alerts from Prometheus Alertmanager via webhook.</li>
              <li>Performs AI-powered root cause analysis using LLM models (Groq/OpenAI).</li>
              <li>Generates automated postmortems.</li>
              <li>Dispatches notifications to Slack and Microsoft Teams.</li>
              <li>Provides chaos simulation for testing detection accuracy.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. Account Responsibilities</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li>You must provide a valid email address to register.</li>
              <li>You are responsible for maintaining the security of your account credentials and webhook token.</li>
              <li>You must not share your webhook token publicly. If compromised, rotate it immediately via the dashboard.</li>
              <li>One account per person. Automated account creation is prohibited.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>Send fabricated or malicious alert data to disrupt the service.</li>
              <li>Attempt to access other users&apos; data or bypass tenant isolation.</li>
              <li>Exceed rate limits (10 registrations/min, 20 logins/min, 120 webhook calls/min).</li>
              <li>Use the Service for any illegal purpose.</li>
              <li>Reverse-engineer the hosted infrastructure (self-hosting the open-source code is permitted).</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. AI-Generated Content Disclaimer</h2>
            <p>
              Root cause analyses, confidence scores, and postmortems are generated by AI models (Groq llama-3.3-70b
              or OpenAI as fallback). These outputs are <strong className="text-white">suggestions, not guarantees</strong>.
              You should always verify AI verdicts before taking production actions. Sentinel-SRE is not liable for
              decisions made based on AI-generated analysis.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Service Availability</h2>
            <p>
              The hosted service runs on Render (backend) and Vercel (frontend) free tiers. We do not
              guarantee uptime, response times, or availability. The backend may experience cold starts
              of up to 30 seconds on the free tier. For production reliability, self-host the platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Open Source License</h2>
            <p>
              Sentinel-SRE source code is available under the MIT License at{' '}
              <a href="https://github.com/sujalmeena7/sentinel-sre" target="_blank" rel="noopener noreferrer" className="text-indigo-400 hover:underline">
                github.com/sujalmeena7/sentinel-sre
              </a>. You are free to self-host, modify, and distribute the code per the MIT License terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Limitation of Liability</h2>
            <p>
              The Service is provided &quot;as is&quot; without warranty of any kind. In no event shall the
              creators of Sentinel-SRE be liable for any damages arising from the use of this Service,
              including but not limited to incorrect AI analysis, data loss, or service downtime.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Termination</h2>
            <p>
              We reserve the right to suspend or terminate accounts that violate these terms or abuse
              the service. You may delete your account at any time by contacting us.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">10. Contact</h2>
            <p>
              For questions about these terms, contact: <a href="mailto:meensujal60@gmail.com" className="text-indigo-400 hover:underline">meensujal60@gmail.com</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
