
route:
  receiver: sentinel-sre

receivers:
  - name: sentinel-sre
    webhook_configs:
      - url: "https://sentinel-backend-box9.onrender.com/api/v1/telemetry/prometheus/CEOTOkoIjB8w4Asv7CehOFcrE6vs9J_ZlXbV95Bd4d8"
        send_resolved: true
